📝 Public README
SSWConsulting/SSW.CleanArchitecture pull request #98
Opened 2023-06-05 11:51 UTC by Hona

2023-06-05 23:27 UTC, danielmackay requested changes

2023-06-05 23:27 UTC, danielmackay commented on README.md
> +    - Using [Wire-Mock](https://wiremock.org/) to mock out external services for controlled Integration Tests
Are we actually using Wire Mock?  If not can we remove this until we've added it in?

2023-06-05 23:27 UTC, danielmackay commented on README.md
> +  - Mutation Testing
Are we actually doing Mutation Testing?  If not can we remove this until we've added it in?

2023-06-05 23:27 UTC, danielmackay commented on README.md
Can you add in a section called `Template Usage` (or similar) and paste in the following content? https://github.com/SSWConsulting/SSW.CleanArchitectureWorkshop.Content/tree/main/02-Cafe365#template-setup

2023-06-05 23:55 UTC, matt-goldman approved these changes

2023-06-06 00:09 UTC, danielmackay approved these changes

2023-06-06 00:09 UTC, merged